---
# tasks file for mysql

- name: General mysql configuration
  include_tasks: configure.yml

- name: Configure if the role is master
  include_tasks: master.yml
  when:
    - mysql_replication_role == 'master'

- name: Configure if the role is slave
  include_tasks: slave.yml
  when:
    - mysql_replication_role == 'slave'

